### ISSUE TITLE
Depandancy issue? 

### ISSUE THREAD

**Issue by Deviiiiant** [kompics/kompics-scala#8]
Hello ! 
After including kompics to my project by adding: 

`resolvers += Resolver.jcenterRepo
resolvers += Resolver.bintrayRepo("kompics", "Maven")

libraryDependencies += "se.sics.kompics" %% "kompics-scala" % "2.0.+"`

I notice a plenty of dependancies are included into my project as well, but everything is fine so far. 
Where I try to print "HelloWorld" by the following codes: 

`import se.sics.kompics.sl._ 

class MyComponent (init : Init[MyComponent]) extends ComponentDefinition {
    val Init = init
    ctrl uponEvent { 
        case _ : Start => {
            print("HelloWorld")
            Kompics.asyncShutdown()
        }
    }
}

object Main { 
    def main(args : Array[String]) { 
        Kompics.createAndStart(classOf[MyComponent])
    }
}`

Two exceptions are thrown. Below are my debug console logs: 

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.RuntimeException: Cannot create main component MyComponent
	at se.sics.kompics.Kompics.createAndStart(Kompics.java:330)
	at se.sics.kompics.Kompics.createAndStart(Kompics.java:259)
	at se.sics.kompics.Kompics.createAndStart(Kompics.java:208)
	at se.sics.kompics.sl.Kompics$.createAndStart(Kompics.scala:82)
	at Main$.main(MyComponent.scala:15)
	at Main.main(MyComponent.scala)
Caused by: java.lang.InstantiationException: MyComponent
`
I use Metals as the language server on vscode. You can find more information from this link: [https://scalameta.org/metals/](url). 

I would appreciate it if you can give some advice  :)

**Comment by Bathtor** [comment]
Remove `val Init = init` and `init : Init[MyComponent]` (from the constructor) and it should work. Your component expects that you pass it an `Init` instance during creation, but you aren't passing it when creating Kompics. Since you aren't using it either, you can just remove it and have a no-argument constructor.

The SLF4J stuff is just complaining that you don't have a logging backend. You can add something like [logback](http://logback.qos.ch/) to get rid of the messages (and see actually logging messages^^).
